import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ReactHookForm from 'components/ReactHookForm'
import { Button } from '@mui/material'

export default function Form() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Form</h1>
      <ReactHookForm />

      <Button variant="outlined" href="./">
        Home
      </Button>
    </div>
  )
}
