import Head from 'next/head'
import { Box, Button } from '@mui/material'
import { Translate } from '@/components/Translate'
import styles from '../src/styles/Home.module.css'
import { TitleSet } from '@/components/TitleSet'

export default function Home({ toggleTheme }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button variant="contained" color="primary" onClick={toggleTheme}>
          Toggle Theme
        </Button>
        <TitleSet
          component="h1"
          variant="h3"
          headingText="Deep Translate for i18n & json"
          subtitleText="日本語から英語に翻訳と同時に、日英セットで各json形式で書き出されます"
        />
        <Box my={2}>
          <Translate />
        </Box>
      </main>
    </div>
  )
}
