// import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import { SampleButton } from 'components/SampleButton'
import useTranslation from 'next-translate/useTranslation'

// export const Home: React.FC = () => {
export default function Home() {
  const { t } = useTranslation()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* <SampleButton label='xxx' size='medium' primary /> */}

        <h2>{t('lang:Japanese')}</h2>
        <h2>{t('lang:English')}</h2>
        <h2>{t('lang:Korean')}</h2>
      </main>
    </div>
  )
}
